apiVersion: v1
kind: Service
metadata:
  name: webook-redis
spec:
  selector:
    app: webook-redis
  ports:
    - protocol: TCP
      # service的端口，集群内访问
      port: 11479
      # pod对外的端口，redis默认6379
      targetPort: 6379
      # 集群外访问
      nodePort: 30003
  type: NodePort
  