apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
  labels:
    app: webook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webook
  template:
    metadata:
      labels:
        app: webook
    spec:
      # hostNetwork: false
      containers:
        - name: webook
          image: acorngrow/webook:v0.0.1
          ports:
            - containerPort: 8081
      